/*
 MIT
 @see https://lunrjs.com
 Copyright (C) 2018 Oliver Nightingale
*/
(function(){var b=function(a){var c=new b.Builder;c.pipeline.add(b.trimmer,b.stopWordFilter,b.stemmer);c.searchPipeline.add(b.stemmer);a.call(c,c);return c.build()};b.version="2.2.1";b.utils={};b.utils.warn=function(a){return function(b){a.console&&console.warn&&console.warn(b)}}(this);b.utils.asString=function(a){return void 0===a||null===a?"":a.toString()};b.utils.clone=function(a){if(null===a||void 0===a)return a;for(var b=Object.create(null),d=Object.keys(a),g=0;g<d.length;g++){var e=d[g],f=a[e];
if(Array.isArray(f))b[e]=f.slice();else if("string"===typeof f||"number"===typeof f||"boolean"===typeof f)b[e]=f;else throw new TypeError("clone is not deep and does not support nested objects");}return b};b.FieldRef=function(a,b,d){this.docRef=a;this.fieldName=b;this._stringValue=d};b.FieldRef.joiner="/";b.FieldRef.fromString=function(a){var c=a.indexOf(b.FieldRef.joiner);if(-1===c)throw"malformed field ref string";var d=a.slice(0,c);c=a.slice(c+1);return new b.FieldRef(c,d,a)};b.FieldRef.prototype.toString=
function(){void 0==this._stringValue&&(this._stringValue=this.fieldName+b.FieldRef.joiner+this.docRef);return this._stringValue};b.Set=function(a){this.elements=Object.create(null);if(a){this.length=a.length;for(var b=0;b<this.length;b++)this.elements[a[b]]=!0}else this.length=0};b.Set.complete={intersect:function(a){return a},union:function(a){return a},contains:function(){return!0}};b.Set.empty={intersect:function(){return this},union:function(a){return a},contains:function(){return!1}};b.Set.prototype.contains=
function(a){return!!this.elements[a]};b.Set.prototype.intersect=function(a){var c=[];if(this.length<a.length)var d=this;else d=a,a=this;d=Object.keys(d.elements);for(var g=0;g<d.length;g++){var e=d[g];e in a.elements&&c.push(e)}return new b.Set(c)};b.Set.prototype.union=function(a){return new b.Set(Object.keys(this.elements).concat(Object.keys(a.elements)))};b.idf=function(a,b){var c=0,g;for(g in a)"_index"!=g&&(c+=Object.keys(a[g]).length);return Math.log(1+Math.abs((b-c+.5)/(c+.5)))};b.Token=function(a,
b){this.str=a||"";this.metadata=b||{}};b.Token.prototype.toString=function(){return this.str};b.Token.prototype.update=function(a){this.str=a(this.str,this.metadata);return this};b.Token.prototype.clone=function(a){a=a||function(a){return a};return new b.Token(a(this.str,this.metadata),this.metadata)};b.tokenizer=function(a,c){if(null==a||void 0==a)return[];if(Array.isArray(a))return a.map(function(a){return new b.Token(b.utils.asString(a).toLowerCase(),b.utils.clone(c))});for(var d=a.toString().trim().toLowerCase(),
g=d.length,e=[],f=0,h=0;f<=g;f++){var k=d.charAt(f),l=f-h;if(k.match(b.tokenizer.separator)||f==g)0<l&&(k=b.utils.clone(c)||{},k.position=[h,l],k.index=e.length,e.push(new b.Token(d.slice(h,f),k))),h=f+1}return e};b.tokenizer.separator=/[\s\-]+/;b.Pipeline=function(){this._stack=[]};b.Pipeline.registeredFunctions=Object.create(null);b.Pipeline.registerFunction=function(a,c){c in this.registeredFunctions&&b.utils.warn("Overwriting existing registered function: "+c);a.label=c;b.Pipeline.registeredFunctions[a.label]=
a};b.Pipeline.warnIfFunctionNotRegistered=function(a){a.label&&a.label in this.registeredFunctions||b.utils.warn("Function is not registered with pipeline. This may cause problems when serialising the index.\n",a)};b.Pipeline.load=function(a){var c=new b.Pipeline;a.forEach(function(a){var d=b.Pipeline.registeredFunctions[a];if(d)c.add(d);else throw Error("Cannot load unregistered function: "+a);});return c};b.Pipeline.prototype.add=function(){Array.prototype.slice.call(arguments).forEach(function(a){b.Pipeline.warnIfFunctionNotRegistered(a);
this._stack.push(a)},this)};b.Pipeline.prototype.after=function(a,c){b.Pipeline.warnIfFunctionNotRegistered(c);var d=this._stack.indexOf(a);if(-1==d)throw Error("Cannot find existingFn");this._stack.splice(d+1,0,c)};b.Pipeline.prototype.before=function(a,c){b.Pipeline.warnIfFunctionNotRegistered(c);var d=this._stack.indexOf(a);if(-1==d)throw Error("Cannot find existingFn");this._stack.splice(d,0,c)};b.Pipeline.prototype.remove=function(a){a=this._stack.indexOf(a);-1!=a&&this._stack.splice(a,1)};b.Pipeline.prototype.run=
function(a){for(var b=this._stack.length,d=0;d<b;d++){for(var g=this._stack[d],e=[],f=0;f<a.length;f++){var h=g(a[f],f,a);if(void 0!==h&&""!==h)if(h instanceof Array)for(var k=0;k<h.length;k++)e.push(h[k]);else e.push(h)}a=e}return a};b.Pipeline.prototype.runString=function(a,c){var d=new b.Token(a,c);return this.run([d]).map(function(a){return a.toString()})};b.Pipeline.prototype.reset=function(){this._stack=[]};b.Pipeline.prototype.toJSON=function(){return this._stack.map(function(a){b.Pipeline.warnIfFunctionNotRegistered(a);
return a.label})};b.Vector=function(a){this._magnitude=0;this.elements=a||[]};b.Vector.prototype.positionForIndex=function(a){if(0==this.elements.length)return 0;for(var b=0,d=this.elements.length/2,g=d-b,e=Math.floor(g/2),f=this.elements[2*e];1<g;){f<a&&(b=e);f>a&&(d=e);if(f==a)break;g=d-b;e=b+Math.floor(g/2);f=this.elements[2*e]}if(f==a||f>a)return 2*e;if(f<a)return 2*(e+1)};b.Vector.prototype.insert=function(a,b){this.upsert(a,b,function(){throw"duplicate index";})};b.Vector.prototype.upsert=function(a,
b,d){this._magnitude=0;var c=this.positionForIndex(a);this.elements[c]==a?this.elements[c+1]=d(this.elements[c+1],b):this.elements.splice(c,0,a,b)};b.Vector.prototype.magnitude=function(){if(this._magnitude)return this._magnitude;for(var a=0,b=this.elements.length,d=1;d<b;d+=2){var g=this.elements[d];a+=g*g}return this._magnitude=Math.sqrt(a)};b.Vector.prototype.dot=function(a){var b=0,d=this.elements;a=a.elements;for(var g=d.length,e=a.length,f,h,k=0,l=0;k<g&&l<e;)f=d[k],h=a[l],f<h?k+=2:f>h?l+=2:
f==h&&(b+=d[k+1]*a[l+1],k+=2,l+=2);return b};b.Vector.prototype.similarity=function(a){return this.dot(a)/(this.magnitude()*a.magnitude())||0};b.Vector.prototype.toArray=function(){for(var a=Array(this.elements.length/2),b=1,d=0;b<this.elements.length;b+=2,d++)a[d]=this.elements[b];return a};b.Vector.prototype.toJSON=function(){return this.elements};b.stemmer=function(){var a={ational:"ate",tional:"tion",enci:"ence",anci:"ance",izer:"ize",bli:"ble",alli:"al",entli:"ent",eli:"e",ousli:"ous",ization:"ize",
ation:"ate",ator:"ate",alism:"al",iveness:"ive",fulness:"ful",ousness:"ous",aliti:"al",iviti:"ive",biliti:"ble",logi:"log"},b={icate:"ic",ative:"",alize:"al",iciti:"ic",ical:"ic",ful:"",ness:""},d=/^([^aeiou][^aeiouy]*)?[aeiouy][aeiou]*[^aeiou][^aeiouy]*/,g=/^([^aeiou][^aeiouy]*)?[aeiouy][aeiou]*[^aeiou][^aeiouy]*[aeiouy][aeiou]*[^aeiou][^aeiouy]*/,e=/^([^aeiou][^aeiouy]*)?[aeiouy][aeiou]*[^aeiou][^aeiouy]*([aeiouy][aeiou]*)?$/,f=/^([^aeiou][^aeiouy]*)?[aeiouy]/,h=/^(.+?)(ss|i)es$/,k=/^(.+?)([^s])s$/,
l=/^(.+?)eed$/,n=/^(.+?)(ed|ing)$/,u=/.$/,x=/(at|bl|iz)$/,v=/([^aeiouylsz])\1$/,r=/^[^aeiou][^aeiouy]*[aeiouy][^aeiouwxy]$/,q=/^(.+?[^aeiou])y$/,A=/^(.+?)(ational|tional|enci|anci|izer|bli|alli|entli|eli|ousli|ization|ation|ator|alism|iveness|fulness|ousness|aliti|iviti|biliti|logi)$/,y=/^(.+?)(icate|ative|alize|iciti|ical|ful|ness)$/,D=/^(.+?)(al|ance|ence|er|ic|able|ible|ant|ement|ment|ent|ou|ism|ate|iti|ous|ive|ize)$/,G=/^(.+?)(s|t)(ion)$/,E=/^(.+?)e$/,B=/ll$/,F=/^[^aeiou][^aeiouy]*[aeiouy][^aeiouwxy]$/,
C=function(c){if(3>c.length)return c;var w=c.substr(0,1);"y"==w&&(c=w.toUpperCase()+c.substr(1));var p=h;var m=k;p.test(c)?c=c.replace(p,"$1$2"):m.test(c)&&(c=c.replace(m,"$1$2"));p=l;m=n;if(p.test(c))m=p.exec(c),p=d,p.test(m[1])&&(p=u,c=c.replace(p,""));else if(m.test(c)){m=m.exec(c);var t=m[1];m=f;if(m.test(t)){c=t;m=x;var z=v;m.test(c)?c+="e":z.test(c)?(p=u,c=c.replace(p,"")):r.test(c)&&(c+="e")}}p=q;p.test(c)&&(m=p.exec(c),t=m[1],c=t+"i");p=A;p.test(c)&&(m=p.exec(c),t=m[1],m=m[2],p=d,p.test(t)&&
(c=t+a[m]));p=y;p.test(c)&&(m=p.exec(c),t=m[1],m=m[2],p=d,p.test(t)&&(c=t+b[m]));p=D;m=G;p.test(c)?(m=p.exec(c),t=m[1],p=g,p.test(t)&&(c=t)):m.test(c)&&(m=m.exec(c),t=m[1]+m[2],m=g,m.test(t)&&(c=t));p=E;p.test(c)&&(m=p.exec(c),t=m[1],p=g,m=e,z=F,p.test(t)||m.test(t)&&!z.test(t))&&(c=t);p=B;m=g;p.test(c)&&m.test(c)&&(p=u,c=c.replace(p,""));"y"==w&&(c=w.toLowerCase()+c.substr(1));return c};return function(a){return a.update(C)}}();b.Pipeline.registerFunction(b.stemmer,"stemmer");b.generateStopWordFilter=
function(a){var b=a.reduce(function(a,b){a[b]=b;return a},{});return function(a){if(a&&b[a.toString()]!==a.toString())return a}};b.stopWordFilter=b.generateStopWordFilter("a able about across after all almost also am among an and any are as at be because been but by can cannot could dear did do does either else ever every for from get got had has have he her hers him his how however i if in into is it its just least let like likely may me might most must my neither no nor not of off often on only or other our own rather said say says she should since so some than that the their them then there these they this tis to too twas us wants was we were what when where which while who whom why will with would yet you your".split(" "));
b.Pipeline.registerFunction(b.stopWordFilter,"stopWordFilter");b.trimmer=function(a){return a.update(function(a){return a.replace(/^\W+/,"").replace(/\W+$/,"")})};b.Pipeline.registerFunction(b.trimmer,"trimmer");b.TokenSet=function(){this["final"]=!1;this.edges={};this.id=b.TokenSet._nextId;b.TokenSet._nextId+=1};b.TokenSet._nextId=1;b.TokenSet.fromArray=function(a){for(var c=new b.TokenSet.Builder,d=0,g=a.length;d<g;d++)c.insert(a[d]);c.finish();return c.root};b.TokenSet.fromClause=function(a){return"editDistance"in
a?b.TokenSet.fromFuzzyString(a.term,a.editDistance):b.TokenSet.fromString(a.term)};b.TokenSet.fromFuzzyString=function(a,c){for(var d=new b.TokenSet,g=[{node:d,editsRemaining:c,str:a}];g.length;){var e=g.pop();if(0<e.str.length){var f=e.str.charAt(0);if(f in e.node.edges)var h=e.node.edges[f];else h=new b.TokenSet,e.node.edges[f]=h;1==e.str.length?h["final"]=!0:g.push({node:h,editsRemaining:e.editsRemaining,str:e.str.slice(1)})}0<e.editsRemaining&&1<e.str.length&&(f=e.str.charAt(1),f in e.node.edges?
h=e.node.edges[f]:(h=new b.TokenSet,e.node.edges[f]=h),2>=e.str.length?h["final"]=!0:g.push({node:h,editsRemaining:e.editsRemaining-1,str:e.str.slice(2)}));0<e.editsRemaining&&1==e.str.length&&(e.node["final"]=!0);0<e.editsRemaining&&1<=e.str.length&&("*"in e.node.edges?f=e.node.edges["*"]:(f=new b.TokenSet,e.node.edges["*"]=f),1==e.str.length?f["final"]=!0:g.push({node:f,editsRemaining:e.editsRemaining-1,str:e.str.slice(1)}));0<e.editsRemaining&&("*"in e.node.edges?f=e.node.edges["*"]:(f=new b.TokenSet,
e.node.edges["*"]=f),0==e.str.length?f["final"]=!0:g.push({node:f,editsRemaining:e.editsRemaining-1,str:e.str}));if(0<e.editsRemaining&&1<e.str.length){f=e.str.charAt(0);h=e.str.charAt(1);if(h in e.node.edges)var k=e.node.edges[h];else k=new b.TokenSet,e.node.edges[h]=k;1==e.str.length?k["final"]=!0:g.push({node:k,editsRemaining:e.editsRemaining-1,str:f+e.str.slice(2)})}}return d};b.TokenSet.fromString=function(a){for(var c=new b.TokenSet,d=c,g=!1,e=0,f=a.length;e<f;e++){var h=a[e],k=e==f-1;if("*"==
h)g=!0,c.edges[h]=c,c["final"]=k;else{var l=new b.TokenSet;l["final"]=k;c=c.edges[h]=l;g&&(c.edges["*"]=d)}}return d};b.TokenSet.prototype.toArray=function(){for(var a=[],b=[{prefix:"",node:this}];b.length;){var d=b.pop(),g=Object.keys(d.node.edges),e=g.length;d.node["final"]&&a.push(d.prefix);for(var f=0;f<e;f++){var h=g[f];b.push({prefix:d.prefix.concat(h),node:d.node.edges[h]})}}return a};b.TokenSet.prototype.toString=function(){if(this._str)return this._str;for(var a=this["final"]?"1":"0",b=Object.keys(this.edges).sort(),
d=b.length,g=0;g<d;g++){var e=b[g];a=a+e+this.edges[e].id}return a};b.TokenSet.prototype.intersect=function(a){for(var c=new b.TokenSet,d=[{qNode:a,output:c,node:this}];d.length;){a=d.pop();for(var g=Object.keys(a.qNode.edges),e=g.length,f=Object.keys(a.node.edges),h=f.length,k=0;k<e;k++)for(var l=g[k],n=0;n<h;n++){var u=f[n];if(u==l||"*"==l){var x=a.node.edges[u],v=a.qNode.edges[l],r=x["final"]&&v["final"];if(u in a.output.edges){var q=a.output.edges[u];q["final"]=q["final"]||r}else q=new b.TokenSet,
q["final"]=r,a.output.edges[u]=q;d.push({qNode:v,output:q,node:x})}}}return c};b.TokenSet.Builder=function(){this.previousWord="";this.root=new b.TokenSet;this.uncheckedNodes=[];this.minimizedNodes={}};b.TokenSet.Builder.prototype.insert=function(a){var c=0;if(a<this.previousWord)throw Error("Out of order word insertion");for(var d=0;d<a.length&&d<this.previousWord.length&&a[d]==this.previousWord[d];d++)c++;this.minimize(c);var g=0==this.uncheckedNodes.length?this.root:this.uncheckedNodes[this.uncheckedNodes.length-
1].child;for(d=c;d<a.length;d++){c=new b.TokenSet;var e=a[d];g.edges[e]=c;this.uncheckedNodes.push({parent:g,"char":e,child:c});g=c}g["final"]=!0;this.previousWord=a};b.TokenSet.Builder.prototype.finish=function(){this.minimize(0)};b.TokenSet.Builder.prototype.minimize=function(a){for(var b=this.uncheckedNodes.length-1;b>=a;b--){var d=this.uncheckedNodes[b],g=d.child.toString();g in this.minimizedNodes?d.parent.edges[d["char"]]=this.minimizedNodes[g]:(d.child._str=g,this.minimizedNodes[g]=d.child);
this.uncheckedNodes.pop()}};b.Index=function(a){this.invertedIndex=a.invertedIndex;this.fieldVectors=a.fieldVectors;this.tokenSet=a.tokenSet;this.fields=a.fields;this.pipeline=a.pipeline};b.Index.prototype.search=function(a){return this.query(function(c){(new b.QueryParser(a,c)).parse()})};b.Index.prototype.query=function(a){for(var c=new b.Query(this.fields),d=Object.create(null),g=Object.create(null),e=Object.create(null),f=Object.create(null),h=Object.create(null),k=0;k<this.fields.length;k++)g[this.fields[k]]=
new b.Vector;a.call(c,c);for(k=0;k<c.clauses.length;k++){var l=c.clauses[k],n=null,u=b.Set.complete;n=l.usePipeline?this.pipeline.runString(l.term,{fields:l.fields}):[l.term];for(var x=0;x<n.length;x++){l.term=n[x];a=b.TokenSet.fromClause(l);var v=this.tokenSet.intersect(a).toArray();if(0===v.length&&l.presence===b.Query.presence.REQUIRED){for(var r=0;r<l.fields.length;r++){var q=l.fields[r];f[q]=b.Set.empty}break}for(var A=0;A<v.length;A++){var y=v[A],D=this.invertedIndex[y],G=D._index;for(r=0;r<
l.fields.length;r++){q=l.fields[r];var E=D[q],B=Object.keys(E),F=y+"/"+q;a=new b.Set(B);l.presence==b.Query.presence.REQUIRED&&(u=u.union(a),void 0===f[q]&&(f[q]=b.Set.complete));if(l.presence==b.Query.presence.PROHIBITED)void 0===h[q]&&(h[q]=b.Set.empty),h[q]=h[q].union(a);else if(g[q].upsert(G,1*l.boost,function(a,b){return a+b}),!e[F]){for(var C=0;C<B.length;C++){var z=B[C];a=new b.FieldRef(z,q);z=E[z];var w;void 0===(w=d[a])?d[a]=new b.MatchData(y,q,z):w.add(y,q,z)}e[F]=!0}}}}if(l.presence===
b.Query.presence.REQUIRED)for(r=0;r<l.fields.length;r++)q=l.fields[r],f[q]=f[q].intersect(u)}e=b.Set.complete;w=b.Set.empty;for(k=0;k<this.fields.length;k++)q=this.fields[k],f[q]&&(e=e.intersect(f[q])),h[q]&&(w=w.union(h[q]));f=Object.keys(d);h=[];q=Object.create(null);if(c.isNegated())for(f=Object.keys(this.fieldVectors),k=0;k<f.length;k++)a=f[k],c=b.FieldRef.fromString(a),d[a]=new b.MatchData;for(k=0;k<f.length;k++)c=b.FieldRef.fromString(f[k]),a=c.docRef,e.contains(a)&&!w.contains(a)&&(l=g[c.fieldName].similarity(this.fieldVectors[c]),
void 0!==(n=q[a])?(n.score+=l,n.matchData.combine(d[c])):(c={ref:a,score:l,matchData:d[c]},q[a]=c,h.push(c)));return h.sort(function(a,b){return b.score-a.score})};b.Index.prototype.toJSON=function(){var a=Object.keys(this.invertedIndex).sort().map(function(a){return[a,this.invertedIndex[a]]},this),c=Object.keys(this.fieldVectors).map(function(a){return[a,this.fieldVectors[a].toJSON()]},this);return{version:b.version,fields:this.fields,fieldVectors:c,invertedIndex:a,pipeline:this.pipeline.toJSON()}};
b.Index.load=function(a){var c={},d={},g=a.fieldVectors,e={},f=a.invertedIndex,h=new b.TokenSet.Builder,k=b.Pipeline.load(a.pipeline);a.version!=b.version&&b.utils.warn("Version mismatch when loading serialised index. Current version of lunr '"+b.version+"' does not match serialized index '"+a.version+"'");for(var l=0;l<g.length;l++){var n=g[l];d[n[0]]=new b.Vector(n[1])}for(l=0;l<f.length;l++)n=f[l],g=n[0],n=n[1],h.insert(g),e[g]=n;h.finish();c.fields=a.fields;c.fieldVectors=d;c.invertedIndex=e;
c.tokenSet=h.root;c.pipeline=k;return new b.Index(c)};b.Builder=function(){this._ref="id";this._fields=[];this.invertedIndex=Object.create(null);this.fieldTermFrequencies={};this.fieldLengths={};this.tokenizer=b.tokenizer;this.pipeline=new b.Pipeline;this.searchPipeline=new b.Pipeline;this.documentCount=0;this._b=.75;this._k1=1.2;this.termIndex=0;this.metadataWhitelist=[]};b.Builder.prototype.ref=function(a){this._ref=a};b.Builder.prototype.field=function(a){this._fields.push(a)};b.Builder.prototype.b=
function(a){this._b=0>a?0:1<a?1:a};b.Builder.prototype.k1=function(a){this._k1=a};b.Builder.prototype.add=function(a){var c=a[this._ref];this.documentCount+=1;for(var d=0;d<this._fields.length;d++){var g=this._fields[d],e=this.tokenizer(a[g],{fields:[g]});e=this.pipeline.run(e);var f=new b.FieldRef(c,g),h=Object.create(null);this.fieldTermFrequencies[f]=h;this.fieldLengths[f]=0;this.fieldLengths[f]+=e.length;for(f=0;f<e.length;f++){var k=e[f];void 0==h[k]&&(h[k]=0);h[k]+=1;if(void 0==this.invertedIndex[k]){var l=
Object.create(null);l._index=this.termIndex;this.termIndex+=1;for(var n=0;n<this._fields.length;n++)l[this._fields[n]]=Object.create(null);this.invertedIndex[k]=l}void 0==this.invertedIndex[k][g][c]&&(this.invertedIndex[k][g][c]=Object.create(null));for(l=0;l<this.metadataWhitelist.length;l++){n=this.metadataWhitelist[l];var u=k.metadata[n];void 0==this.invertedIndex[k][g][c][n]&&(this.invertedIndex[k][g][c][n]=[]);this.invertedIndex[k][g][c][n].push(u)}}}};b.Builder.prototype.calculateAverageFieldLengths=
function(){for(var a=Object.keys(this.fieldLengths),c=a.length,d={},g={},e=0;e<c;e++){var f=b.FieldRef.fromString(a[e]),h=f.fieldName;g[h]||(g[h]=0);g[h]+=1;d[h]||(d[h]=0);d[h]+=this.fieldLengths[f]}for(e=0;e<this._fields.length;e++)h=this._fields[e],d[h]/=g[h];this.averageFieldLength=d};b.Builder.prototype.createFieldVectors=function(){for(var a={},c=Object.keys(this.fieldTermFrequencies),d=c.length,g=Object.create(null),e=0;e<d;e++){for(var f=b.FieldRef.fromString(c[e]),h=f.fieldName,k=this.fieldLengths[f],
l=new b.Vector,n=this.fieldTermFrequencies[f],u=Object.keys(n),x=u.length,v=0;v<x;v++){var r=u[v],q=n[r],A=this.invertedIndex[r]._index;if(void 0===g[r]){var y=b.idf(this.invertedIndex[r],this.documentCount);g[r]=y}else y=g[r];l.insert(A,Math.round(y*(this._k1+1)*q/(this._k1*(1-this._b+k/this.averageFieldLength[h]*this._b)+q)*1E3)/1E3)}a[f]=l}this.fieldVectors=a};b.Builder.prototype.createTokenSet=function(){this.tokenSet=b.TokenSet.fromArray(Object.keys(this.invertedIndex).sort())};b.Builder.prototype.build=
function(){this.calculateAverageFieldLengths();this.createFieldVectors();this.createTokenSet();return new b.Index({invertedIndex:this.invertedIndex,fieldVectors:this.fieldVectors,tokenSet:this.tokenSet,fields:this._fields,pipeline:this.searchPipeline})};b.Builder.prototype.use=function(a){var b=Array.prototype.slice.call(arguments,1);b.unshift(this);a.apply(this,b)};b.MatchData=function(a,b,d){for(var c=Object.create(null),e=Object.keys(d||{}),f=0;f<e.length;f++){var h=e[f];c[h]=d[h].slice()}this.metadata=
Object.create(null);void 0!==a&&(this.metadata[a]=Object.create(null),this.metadata[a][b]=c)};b.MatchData.prototype.combine=function(a){for(var b=Object.keys(a.metadata),d=0;d<b.length;d++){var g=b[d],e=Object.keys(a.metadata[g]);void 0==this.metadata[g]&&(this.metadata[g]=Object.create(null));for(var f=0;f<e.length;f++){var h=e[f],k=Object.keys(a.metadata[g][h]);void 0==this.metadata[g][h]&&(this.metadata[g][h]=Object.create(null));for(var l=0;l<k.length;l++){var n=k[l];this.metadata[g][h][n]=void 0==
this.metadata[g][h][n]?a.metadata[g][h][n]:this.metadata[g][h][n].concat(a.metadata[g][h][n])}}}};b.MatchData.prototype.add=function(a,b,d){if(a in this.metadata)if(b in this.metadata[a])for(var c=Object.keys(d),e=0;e<c.length;e++){var f=c[e];this.metadata[a][b][f]=f in this.metadata[a][b]?this.metadata[a][b][f].concat(d[f]):d[f]}else this.metadata[a][b]=d;else this.metadata[a]=Object.create(null),this.metadata[a][b]=d};b.Query=function(a){this.clauses=[];this.allFields=a};b.Query.wildcard=new String("*");
b.Query.wildcard.NONE=0;b.Query.wildcard.LEADING=1;b.Query.wildcard.TRAILING=2;b.Query.presence={OPTIONAL:1,REQUIRED:2,PROHIBITED:3};b.Query.prototype.clause=function(a){"fields"in a||(a.fields=this.allFields);"boost"in a||(a.boost=1);"usePipeline"in a||(a.usePipeline=!0);"wildcard"in a||(a.wildcard=b.Query.wildcard.NONE);a.wildcard&b.Query.wildcard.LEADING&&a.term.charAt(0)!=b.Query.wildcard&&(a.term="*"+a.term);a.wildcard&b.Query.wildcard.TRAILING&&a.term.slice(-1)!=b.Query.wildcard&&(a.term=""+
a.term+"*");"presence"in a||(a.presence=b.Query.presence.OPTIONAL);this.clauses.push(a);return this};b.Query.prototype.isNegated=function(){for(var a=0;a<this.clauses.length;a++)if(this.clauses[a].presence!=b.Query.presence.PROHIBITED)return!1;return!0};b.Query.prototype.term=function(a,b){if(Array.isArray(a))return a.forEach(function(a){this.term(a,b)},this),this;var c=b||{};c.term=a.toString();this.clause(c);return this};b.QueryParseError=function(a,b,d){this.name="QueryParseError";this.message=
a;this.start=b;this.end=d};b.QueryParseError.prototype=Error();b.QueryLexer=function(a){this.lexemes=[];this.str=a;this.length=a.length;this.start=this.pos=0;this.escapeCharPositions=[]};b.QueryLexer.prototype.run=function(){for(var a=b.QueryLexer.lexText;a;)a=a(this)};b.QueryLexer.prototype.sliceString=function(){for(var a=[],b=this.start,d,g=0;g<this.escapeCharPositions.length;g++)d=this.escapeCharPositions[g],a.push(this.str.slice(b,d)),b=d+1;a.push(this.str.slice(b,this.pos));this.escapeCharPositions.length=
0;return a.join("")};b.QueryLexer.prototype.emit=function(a){this.lexemes.push({type:a,str:this.sliceString(),start:this.start,end:this.pos});this.start=this.pos};b.QueryLexer.prototype.escapeCharacter=function(){this.escapeCharPositions.push(this.pos-1);this.pos+=1};b.QueryLexer.prototype.next=function(){if(this.pos>=this.length)return b.QueryLexer.EOS;var a=this.str.charAt(this.pos);this.pos+=1;return a};b.QueryLexer.prototype.width=function(){return this.pos-this.start};b.QueryLexer.prototype.ignore=
function(){this.start==this.pos&&(this.pos+=1);this.start=this.pos};b.QueryLexer.prototype.backup=function(){--this.pos};b.QueryLexer.prototype.acceptDigitRun=function(){do{var a=this.next();var c=a.charCodeAt(0)}while(47<c&&58>c);a!=b.QueryLexer.EOS&&this.backup()};b.QueryLexer.prototype.more=function(){return this.pos<this.length};b.QueryLexer.EOS="EOS";b.QueryLexer.FIELD="FIELD";b.QueryLexer.TERM="TERM";b.QueryLexer.EDIT_DISTANCE="EDIT_DISTANCE";b.QueryLexer.BOOST="BOOST";b.QueryLexer.PRESENCE=
"PRESENCE";b.QueryLexer.lexField=function(a){a.backup();a.emit(b.QueryLexer.FIELD);a.ignore();return b.QueryLexer.lexText};b.QueryLexer.lexTerm=function(a){1<a.width()&&(a.backup(),a.emit(b.QueryLexer.TERM));a.ignore();if(a.more())return b.QueryLexer.lexText};b.QueryLexer.lexEditDistance=function(a){a.ignore();a.acceptDigitRun();a.emit(b.QueryLexer.EDIT_DISTANCE);return b.QueryLexer.lexText};b.QueryLexer.lexBoost=function(a){a.ignore();a.acceptDigitRun();a.emit(b.QueryLexer.BOOST);return b.QueryLexer.lexText};
b.QueryLexer.lexEOS=function(a){0<a.width()&&a.emit(b.QueryLexer.TERM)};b.QueryLexer.termSeparator=b.tokenizer.separator;b.QueryLexer.lexText=function(a){for(;;){var c=a.next();if(c==b.QueryLexer.EOS)return b.QueryLexer.lexEOS;if(92==c.charCodeAt(0))a.escapeCharacter();else{if(":"==c)return b.QueryLexer.lexField;if("~"==c)return a.backup(),0<a.width()&&a.emit(b.QueryLexer.TERM),b.QueryLexer.lexEditDistance;if("^"==c)return a.backup(),0<a.width()&&a.emit(b.QueryLexer.TERM),b.QueryLexer.lexBoost;if("+"==
c&&1===a.width()||"-"==c&&1===a.width())return a.emit(b.QueryLexer.PRESENCE),b.QueryLexer.lexText;if(c.match(b.QueryLexer.termSeparator))return b.QueryLexer.lexTerm}}};b.QueryParser=function(a,c){this.lexer=new b.QueryLexer(a);this.query=c;this.currentClause={};this.lexemeIdx=0};b.QueryParser.prototype.parse=function(){this.lexer.run();this.lexemes=this.lexer.lexemes;for(var a=b.QueryParser.parseClause;a;)a=a(this);return this.query};b.QueryParser.prototype.peekLexeme=function(){return this.lexemes[this.lexemeIdx]};
b.QueryParser.prototype.consumeLexeme=function(){var a=this.peekLexeme();this.lexemeIdx+=1;return a};b.QueryParser.prototype.nextClause=function(){this.query.clause(this.currentClause);this.currentClause={}};b.QueryParser.parseClause=function(a){a=a.peekLexeme();if(void 0!=a)switch(a.type){case b.QueryLexer.PRESENCE:return b.QueryParser.parsePresence;case b.QueryLexer.FIELD:return b.QueryParser.parseField;case b.QueryLexer.TERM:return b.QueryParser.parseTerm;default:var c="expected either a field or a term, found "+
a.type;1<=a.str.length&&(c+=" with value '"+a.str+"'");throw new b.QueryParseError(c,a.start,a.end);}};b.QueryParser.parsePresence=function(a){var c=a.consumeLexeme();if(void 0!=c){switch(c.str){case "-":a.currentClause.presence=b.Query.presence.PROHIBITED;break;case "+":a.currentClause.presence=b.Query.presence.REQUIRED;break;default:throw a="unrecognised presence operator'"+c.str+"'",new b.QueryParseError(a,c.start,c.end);}var d=a.peekLexeme();if(void 0==d)throw new b.QueryParseError("expecting term or field, found nothing",
c.start,c.end);switch(d.type){case b.QueryLexer.FIELD:return b.QueryParser.parseField;case b.QueryLexer.TERM:return b.QueryParser.parseTerm;default:throw a="expecting term or field, found '"+d.type+"'",new b.QueryParseError(a,d.start,d.end);}}};b.QueryParser.parseField=function(a){var c=a.consumeLexeme();if(void 0!=c){if(-1==a.query.allFields.indexOf(c.str))throw a=a.query.allFields.map(function(a){return"'"+a+"'"}).join(", "),a="unrecognised field '"+c.str+"', possible fields: "+a,new b.QueryParseError(a,
c.start,c.end);a.currentClause.fields=[c.str];var d=a.peekLexeme();if(void 0==d)throw new b.QueryParseError("expecting term, found nothing",c.start,c.end);switch(d.type){case b.QueryLexer.TERM:return b.QueryParser.parseTerm;default:throw a="expecting term, found '"+d.type+"'",new b.QueryParseError(a,d.start,d.end);}}};b.QueryParser.parseTerm=function(a){var c=a.consumeLexeme();if(void 0!=c)if(a.currentClause.term=c.str.toLowerCase(),-1!=c.str.indexOf("*")&&(a.currentClause.usePipeline=!1),c=a.peekLexeme(),
void 0==c)a.nextClause();else switch(c.type){case b.QueryLexer.TERM:return a.nextClause(),b.QueryParser.parseTerm;case b.QueryLexer.FIELD:return a.nextClause(),b.QueryParser.parseField;case b.QueryLexer.EDIT_DISTANCE:return b.QueryParser.parseEditDistance;case b.QueryLexer.BOOST:return b.QueryParser.parseBoost;case b.QueryLexer.PRESENCE:return a.nextClause(),b.QueryParser.parsePresence;default:throw new b.QueryParseError("Unexpected lexeme type '"+c.type+"'",c.start,c.end);}};b.QueryParser.parseEditDistance=
function(a){var c=a.consumeLexeme();if(void 0!=c){var d=parseInt(c.str,10);if(isNaN(d))throw new b.QueryParseError("edit distance must be numeric",c.start,c.end);a.currentClause.editDistance=d;c=a.peekLexeme();if(void 0==c)a.nextClause();else switch(c.type){case b.QueryLexer.TERM:return a.nextClause(),b.QueryParser.parseTerm;case b.QueryLexer.FIELD:return a.nextClause(),b.QueryParser.parseField;case b.QueryLexer.EDIT_DISTANCE:return b.QueryParser.parseEditDistance;case b.QueryLexer.BOOST:return b.QueryParser.parseBoost;
default:throw a="Unexpected lexeme type '"+c.type+"'",new b.QueryParseError(a,c.start,c.end);}}};b.QueryParser.parseBoost=function(a){var c=a.consumeLexeme();if(void 0!=c){var d=parseInt(c.str,10);if(isNaN(d))throw new b.QueryParseError("boost must be numeric",c.start,c.end);a.currentClause.boost=d;c=a.peekLexeme();if(void 0==c)a.nextClause();else switch(c.type){case b.QueryLexer.TERM:return a.nextClause(),b.QueryParser.parseTerm;case b.QueryLexer.FIELD:return a.nextClause(),b.QueryParser.parseField;
case b.QueryLexer.EDIT_DISTANCE:return b.QueryParser.parseEditDistance;case b.QueryLexer.BOOST:return b.QueryParser.parseBoost;default:throw a="Unexpected lexeme type '"+c.type+"'",new b.QueryParseError(a,c.start,c.end);}}};(function(a,b){"function"===typeof define&&define.amd?define(b):"object"===typeof exports?module.exports=b():a.lunr=b()})(this,function(){return b})})();